name: ビルド & デプロイ

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Node.js セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 19.0.1

      - name: npm セットアップ
        run: npm install -g npm@9.1.1

      - name: パッケージインストール
        run: npm install
        working-directory: ./app/

      - name: ビルド
        run: npm run build
        working-directory: ./app/

      - name: ビルド結果を圧縮
        run: tar -zcvf ./build.tar.gz ./dist/
        working-directory: ./app/

      - name: デプロイ
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -oStrictHostKeyChecking=no -i private_key ${{ secrets.HOST }} -l ${{ secrets.USER }} -p ${{ secrets.PORT }} "mkdir -p ${{ secrets.DOCUMENT_ROOT }} && cd ${{ secrets.DOCUMENT_ROOT }} && rm -rf *"
          scp -oStrictHostKeyChecking=no -i private_key -P ${{ secrets.PORT }} ./build.tar.gz ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DOCUMENT_ROOT }}
          ssh -oStrictHostKeyChecking=no -i private_key ${{ secrets.HOST }} -l ${{ secrets.USER }} -p ${{ secrets.PORT }} "cd ${{ secrets.DOCUMENT_ROOT }} && tar xvzf ./build.tar.gz -C ./ --strip-components 2 && rm ./build.tar.gz"
        working-directory: ./app/
